language: node_js
node_js:
  - "8"
  - "9"
  - "10"
install:
  - npm install
addons:
  chrome: stable
sudo: required
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
jobs:
 include:
   - stage: test
     script:
       - node --version
       - npm --version
       - npm update
       - echo "Testing Started ..."
       - npm run test
       - echo "Testing Finished."